// Code generated by MockGen. DO NOT EDIT.
// Source: /home/mia/tech-test-adevinta/src/services/stats.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/thdelmas/tech-test-adevinta/models"
)

// MockStatsServiceInterface is a mock of StatsServiceInterface interface.
type MockStatsServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceInterfaceMockRecorder
}

// MockStatsServiceInterfaceMockRecorder is the mock recorder for MockStatsServiceInterface.
type MockStatsServiceInterfaceMockRecorder struct {
	mock *MockStatsServiceInterface
}

// NewMockStatsServiceInterface creates a new mock instance.
func NewMockStatsServiceInterface(ctrl *gomock.Controller) *MockStatsServiceInterface {
	mock := &MockStatsServiceInterface{ctrl: ctrl}
	mock.recorder = &MockStatsServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsServiceInterface) EXPECT() *MockStatsServiceInterfaceMockRecorder {
	return m.recorder
}

// GetMostFrequentRequest mocks base method.
func (m *MockStatsServiceInterface) GetMostFrequentRequest() (models.FizzBuzzRequest, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMostFrequentRequest")
	ret0, _ := ret[0].(models.FizzBuzzRequest)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMostFrequentRequest indicates an expected call of GetMostFrequentRequest.
func (mr *MockStatsServiceInterfaceMockRecorder) GetMostFrequentRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMostFrequentRequest", reflect.TypeOf((*MockStatsServiceInterface)(nil).GetMostFrequentRequest))
}

// TrackRequest mocks base method.
func (m *MockStatsServiceInterface) TrackRequest(req models.FizzBuzzRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackRequest", req)
}

// TrackRequest indicates an expected call of TrackRequest.
func (mr *MockStatsServiceInterfaceMockRecorder) TrackRequest(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRequest", reflect.TypeOf((*MockStatsServiceInterface)(nil).TrackRequest), req)
}
